"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Building2, Eye, EyeOff, Flame, Gift, Hammer, Heart, LockKeyhole, Mail, ShieldCheck, Truck, Undo2, Wrench } from "lucide-react";
import { request } from "@/lib/storefront-client";
import type { Product } from "@/types";
import { ProductImage } from "@/components/commerce/product-image";
import { formatPrice } from "@/lib/format";
import { useCartStore } from "@/lib/cart-store";
import styles from "./registration.module.css";

export function Registration({ products }: { products: Product[] }) {
  const [type, setType] = useState("trade");
  const [visible, setVisible] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [registered, setRegistered] = useState(false);
  const [email, setEmail] = useState("");
  const [filter, setFilter] = useState("Featured Kits");
  const wishlist = useCartStore((s) => s.wishlist);
  const toggleWishlist = useCartStore((s) => s.toggleWishlist);
  const shown = products.filter((p) => filter === "Featured Kits" || (filter === "Combi Drills" ? /combi/i.test(p.name) : filter === "Twin Packs" ? /twin|2.pack|2.piece/i.test(p.name) : /18v/i.test(p.name)));
  return <div className={styles.page}><div className="border-b border-border-default bg-surface-white"><div className="mx-auto flex max-w-[1600px] flex-wrap items-center gap-2 px-4 py-3 text-label-sm font-label-sm text-text-secondary sm:px-margin-desktop"><nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-1"><Link href="/" className="flex items-center hover:underline"><span aria-hidden className="material-symbols-outlined text-[16px]">home</span><span className="sr-only">Home</span></Link><span aria-hidden>/</span><span className="font-semibold text-text-primary">Create Account</span></nav></div></div>
    <div className={styles.layout}><div><section className={styles.formCard} aria-labelledby="register-heading">
      <div className={styles.topline}><span><Gift size={12} />NEW ACCOUNT INCENTIVE</span><small>{registered ? "Check your email" : "Step 1 of 2: Setup Credentials"}</small></div>
      <h1 id="register-heading">Power Your Jobsite &amp; Home.<br /><em>Claim 15% Off</em> First Order.</h1><p className={styles.intro}>Join 45,000+ UK contractors, mechanical teams, and master builders. Get commercial net-30 terms, direct trade discounts, and live delivery dispatch tracking.</p>
      {registered ? <div className={styles.success} role="status"><BadgeCheck size={32} /><h2>Your account has been created</h2><p>Check {email} for your verification email. Trade approval and promotional discounts are not automatically activated with registration.</p><Link href="/">Continue shopping <ArrowRight size={15} /></Link></div> : <>
      <div className={styles.accountTypes}><button type="button" aria-pressed={type === "trade"} onClick={() => setType("trade")}><Building2 size={18} /><span>Trade &amp; Contractor<small>Net 30, VAT-exempt &amp; pallet rates</small></span></button><button type="button" aria-pressed={type === "retail"} onClick={() => setType("retail")}><Hammer size={18} /><span>Retail &amp; DIY Maker<small>Price match, project lists, fast delivery</small></span></button></div>
      <div className={styles.notice}><ShieldCheck size={18} /><p><strong>{type === "trade" ? "Trade Verified Privileges Pathway" : "Built for your next project"}</strong>{type === "trade" ? "Create your customer account today. Trade credit and company accreditation are not yet available online." : "Save your favourite tools and keep your details ready for your next order."}</p></div>
      <form className={styles.form} onSubmit={async (event) => {event.preventDefault(); if(busy)return; const data = new FormData(event.currentTarget);setError("");setBusy(true);try { await request("auth/register", { method: "POST", body: JSON.stringify({ firstName: String(data.get("firstName")).trim(), lastName: String(data.get("lastName")).trim(), email: email.trim(), password: data.get("password"), phone: String(data.get("phone") || "").trim() || undefined }) });setRegistered(true);}catch(err){setError(err instanceof Error ? err.message : "Registration failed. Please try again.");}finally{setBusy(false);}}}>
        <div className={styles.twoColumns}><label>First Name <b>*</b><input name="firstName" autoComplete="given-name" placeholder="e.g. David" required maxLength={120} /></label><label>Last Name <b>*</b><input name="lastName" autoComplete="family-name" placeholder="e.g. Sterling" required maxLength={120} /></label></div>
        <label>Work / Business Email <b>*</b><div className={styles.inputIcon}><Mail size={15} /><input name="email" type="email" autoComplete="email" placeholder="d.sterling@apexmechanical.co.uk" value={email} onChange={(e) => setEmail(e.target.value)} maxLength={255} required /></div></label>
        <label>Jobsite Dispatch Mobile<div className={styles.inputIcon}><input name="phone" type="tel" autoComplete="tel" placeholder="+44 7700 900077" maxLength={30} /></div></label>
        {type === "trade" && <fieldset className={styles.company} disabled><legend><Building2 size={14} />Company Accreditation Details <small>Coming soon</small></legend><div className={styles.twoColumns}><label>Registered Business Name<input placeholder="Apex Mechanical Ltd" /></label><label>UK VAT Registration #<input placeholder="GB 987 6543 21" /></label><label>Primary Trade Discipline<select defaultValue=""><option value="">Commercial Electrical &amp; High Voltage</option></select></label><label>Est. Monthly Tooling Spend<select defaultValue=""><option value="">£2,500 – £10,000 / month</option></select></label></div></fieldset>}
        <label>Create Password <b>*</b><small className={styles.passwordHint}>At least 10 characters</small><div className={styles.inputIcon}><LockKeyhole size={15} /><input name="password" type={visible ? "text" : "password"} autoComplete="new-password" minLength={10} maxLength={128} required placeholder="Minimum 10 characters" /><button type="button" onClick={() => setVisible(!visible)} aria-label={visible ? "Hide password" : "Show password"}>{visible ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label>
        <div className={styles.offer}><Gift size={23} /><div><strong>BLV-WELCOME15</strong><p>Welcome offer subject to eligibility and checkout validation.</p></div><b>−15%</b></div>
        <label className={styles.check}><input type="checkbox" required />I confirm these details are correct and want to create a Buildivo account.</label>
        {error && <p role="alert" className={styles.error}>{error}</p>}<button className={styles.submit} disabled={busy} type="submit">{busy ? "Creating your account…" : "Create Free Account"}<ArrowRight size={16} /></button>
      </form><p className="mt-5 text-center text-xs text-text-secondary">Already have an account? <Link href="/login" className="font-semibold text-orange-600">Sign in here</Link></p><div className={styles.social}><span>OR RAPID REGISTER WITH</span><div><button disabled>Google Workspace</button><button disabled>Apple ID</button></div><small>Social registration is not available yet.</small></div></>}
    </section><div className={styles.trust}>{[[LockKeyhole,"256-Bit SSL","Bank-grade vault"],[BadgeCheck,"ISO 9001:2015","Quality certified"],[ShieldCheck,"Cyber Essentials","UK secured"],[Undo2,"30-Day Returns","Jobsite collection"]].map(([Icon,title,caption]) => {const Symbol=Icon as typeof LockKeyhole;return <div key={String(title)}><Symbol size={16}/><span><strong>{String(title)}</strong><small>{String(caption)}</small></span></div>;})}</div></div>
    <aside className={styles.sidebar} aria-label="Trending jobsite essentials"><header><Flame size={22}/><div><h2>Trending Jobsite Essentials</h2><p>Explore popular tools and jobsite essentials for your first order</p><small>Live Dispatch: Ready</small></div></header><div className={styles.filters}>{["Featured Kits","Combi Drills","Twin Packs","Heavy Duty 18V"].map((name)=><button key={name} aria-pressed={filter===name} onClick={()=>setFilter(name)}>{name}</button>)}</div>
      {shown.map((p)=><article className={styles.product} key={p.id}><Link href={`/p/${p.slug}`} className={styles.productImage}><ProductImage src={p.image} categorySlug={p.categorySlug} className={styles.image}/><span>SKU: {p.sku}</span></Link><div><button className={styles.wishlist} aria-label={`Save ${p.name}`} aria-pressed={wishlist.includes(p.id)} onClick={()=>toggleWishlist(p.id)}><Heart size={14} fill={wishlist.includes(p.id)?"currentColor":"none"}/></button><small className={styles.rating}>★★★★★ <span>{p.rating.toFixed(1)} ({p.reviewCount} reviews)</span></small><h3><Link href={`/p/${p.slug}`}>{p.name}</Link></h3><p>{p.specs.slice(0,3).map(s=>s.value).join(" · ")}</p><strong className={styles.price}>{formatPrice(p.priceIncVat)}</strong>{p.compareAtIncVat && <s>{formatPrice(p.compareAtIncVat)}</s>}<small className={styles.stock}>{p.stockCount !== undefined ? `${p.stockCount} in stock` : p.deliveryEta}</small></div></article>)}
      {!shown.length && <p className={styles.empty}>No products in this selection. Try Featured Kits.</p>}
      <div className={styles.sidebarTrust}><span><BadgeCheck/>100% Genuine OEM Warranties</span><span><Truck/>Free Next-Day Delivery £75</span><span><Undo2/>30-Day Hassle-Free Returns</span><span><Wrench/>Dedicated trade support</span></div>
    </aside></div></div>;
}
